---
# tasks file for k8s_slave
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Add K8s GPG apt Key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add k8s Repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true
- name: Update apt and install docker-ce and docker-compose
  apt:
    pkg:
      - docker
      - docker.io
      - docker-compose
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Installing kubeadm & iproute on Slave Node
  package:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present

- name: Staring & enabling Docker & kubelet on Slave Node
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ service_names }}"


- name: Restart Docker on Slave Node
  service:
    name: docker
    state: restarted


- name: Joining the master node
  command: "{{ hostvars[groups['aws_k8s_master_host'][0]]['token']['stdout'] }}"

- name: Cleaning Caches on RAM
  shell: echo 3 > /proc/sys/vm/drop_caches
