---
- name: Checking SSH connectivity to Kubernetes Master Instance
  hosts: localhost
  tasks:
    - name: Wait for AWS Instance SSH to come up
      wait_for:
        host: "{{ groups['aws_k8s_master_host'][0] }}"
        port: 22
        state: started

- name: Deploying Kubernetes Master Role on AWS Instance
  hosts: aws_k8s_master_host
  roles:
    - role: k8s_master

- name: Checking SSH connectivity to Kubernetes Slave Instances
  hosts: localhost
  tasks:
    - name: Wait for Worker Instance SSH to come up
      wait_for:
        host: "{{ groups['aws_k8s_worker_host'][0] }}"
        port: 22
        state: started

- name: Deploying Kubernetes Slave Role on AWS Instances
  hosts: aws_k8s_worker_host
  gather_facts: no
  roles:
    - role: k8s_slave
...
